### ISSUE TITLE
Investigate memory leak in prod

### ISSUE THREAD

**Issue by jeffmendoza** [ossf/allstar#381]
A little while ago, I deployed prod and noticed that we were not getting through a full enforce loop. Looking at memory usage there seemed to be a memory leak which was causing allstar to crash before completing a loop. I took a look at the changes between the last two prod pushes and only two seems like they could cause any changes: #345 and #347.

I tried to reproduce the memory leak both in staging and on a personal test instance without any luck. Therefore, I rolled back those two changes with #357, and the leak was fixed.

I need to try to apply the original two changes individually to prod to see which one is the issue, then debug the memory leak.

**Comment by coheigea** [comment]
@jeffmendoza As 4.10.5 is now released, it might make sense to add back the changes and update to 4.10.5 to see if the issue might have been fixed since 4.10.2.

**Comment by coheigea** [comment]
Any idea when this might be fixed @jeffmendoza ? Sorry to push, but scorecards is currently broken on all private repos due to the old version we're using.

**Comment by jeffmendoza** [comment]
Ah, I hadn't prioritized it as I thought the old version of scorecard was working ok. Sorry about that.

I created a new branch https://github.com/ossf/allstar/tree/prod-temp to deploy prod from to not have churn on main. I  deployed the vuln client and will watch it over the weekend and see if it is running out of memory, next I'll try the latest scorecard.

So far the vuln client is looking ok:
![image](https://user-images.githubusercontent.com/771387/230684965-50ff2726-4e90-49c1-a854-144605615336.png)
Which doesn't bode well for the scorecard update. I might have to do a binary search on the scorecard version releases to find out which one is breaking us.

**Comment by coheigea** [comment]
Thanks @jeffmendoza , how is the scorecard update looking?

**Comment by jeffmendoza** [comment]
Just removed the vlun client and left it disabled, then updated to v4.10.2:
![image](https://user-images.githubusercontent.com/771387/231538971-bbc8fd6d-60e5-472f-8b53-17e896b34f46.png)

Going to try v4.10.5 now, then if that is not working, try some of the versions between 4.5 and 4.10

**Comment by jeffmendoza** [comment]
I've deployed a ton and found the change that causes the problem:

https://github.com/ossf/scorecard/commit/9a9a1cbbb79a32ec23d51ddc6aaa06632de0d58e

Not a leak per-se, but an overuse of memory. We call in here: https://github.com/ossf/allstar/blob/main/pkg/scorecard/scorecard.go#L105 And the transport comes from the github client which we create here: https://github.com/ossf/allstar/blob/main/pkg/ghclients/ghclients.go#L102

The transport has the auth already setup which is what we need to pass to scorecard (we don't set any kind of github token env var for scorecard). It also has caching in place for all the calls we do to to the API.

Looks like the change uses the client for tarball downloads, so now our in-memory cache is trying to save the tarballs of many thousands of repos, which is not going to work.

Seems like we have a few areas to investigate

- Can we pass an authenticated but non-cached transport to scorecard
- Can we tweak our caching package to not cache the large tarballs.
- Should we be calling / using scorecard in a different way to provide auth, but not try to cache tarball downloads.

**Comment by coheigea** [comment]
Thanks @jeffmendoza . One thing I spotted looking at the code is that the scorecard Close function is never called on an error in the enforcer loop, I think I fixed this here: https://github.com/ossf/allstar/pull/403

I doubt this is the cause of the memory issue, but maybe you could test with it?

**Comment by jeffmendoza** [comment]
Sounds good, I'll test that as well. Prod does have a number of installations that hit errors.

**Comment by coheigea** [comment]
Any improvement with the PR @jeffmendoza  ?

**Comment by spencerschrock** [comment]
> Can we pass an authenticated but non-cached transport to scorecard

What led to the cache being used in the first place, or rather would using a non-cached transport with scorecard still have any benefits?

> Can we tweak our caching package to not cache the large tarballs.

Would that just involve ignoring certain files here?
https://github.com/ossf/allstar/blob/d199777fe882b0eae837fe9601ad67ec98643761/pkg/ghclients/memorycache.go#L52-L62

Scorecard stores its files in `/tmp` folders using some defined patterns.
https://github.com/ossf/scorecard/blob/46c6fe700cdc10a780f3c867b36b6810e1986cb0/clients/githubrepo/tarball.go#L138-L144

Where the patterns used are:
```
	repoDir      = "repo*"
	repoFilename = "githubrepo*.tar.gz"
```
So for a given repo you may see the tarball downloaded to:
`/tmp/repo2046618022/githubrepo2124655200.tar.gz`

> Should we be calling / using scorecard in a different way to provide auth, but not try to cache tarball downloads.

As of right now alternatives to how you're interacting with scorecard clients. Theres no customization for using different transports used for different private handlers inside the client. 

If it were necessary for a change on our end to allow using a different transport for the tarball download, I would imagine using a "functional options" pattern to set the tarball http client separately (which may expose some of the implementation details that we're hiding away).
This would bring us back to your first point of " Can we pass an authenticated but non-cached transport to scorecard" except only applied to the tarball handler.

**Comment by jeffmendoza** [comment]
> What led to the cache being used in the first place, or rather would using a non-cached transport with scorecard still have any benefits?

Passing the cached transport to Scorecard was a side-effect of needing to pass a pre-authenticated transport. Allstar does a lot of API calls and passes around an authenticated and cached github client to do so. We pull the transport out of the client and pass to Scorecard because it is convenient. It is not critical that the Scorecard API calls are cached, I believe they are minimal, and the most-used checks are just based on the tarball download, and not API calls.

> Would that just involve ignoring certain files here?

Yeah, that could work, I believe the key is the url path, there could be a glob/regex to avoid caching tarballs there.

**Comment by coheigea** [comment]
@jeffmendoza Did my PR make any difference to the memory consumption?

**Comment by jeffmendoza** [comment]
Ah, no unfortunately. It the caching we do on our side, not the Close() needed for the scorecard side.
